// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tryout struct {
	ID              pgtype.UUID
	Title           string
	Description     pgtype.Text
	LongDescription pgtype.Text
	Category        pgtype.Text
	Duration        pgtype.Int4
	Difficulty      pgtype.Text
	PassingScore    pgtype.Int4
	MaxAttempt      pgtype.Int4
	Topics          []string
	CreatorID       pgtype.UUID
	CreatedAt       pgtype.Timestamp
	IsPublished     bool
}

type TryoutAttempt struct {
	ID        pgtype.UUID
	TryoutID  pgtype.UUID
	UserID    pgtype.UUID
	Score     int32
	CreatedAt pgtype.Timestamp
}

type TryoutEssayAttempt struct {
	ID              pgtype.UUID
	TryoutID        pgtype.UUID
	TryoutAttemptID pgtype.UUID
	UserID          pgtype.UUID
	QuestionID      pgtype.UUID
	Answer          string
	Score           int32
	CreatedAt       pgtype.Timestamp
}

type TryoutEssayQuestion struct {
	ID        pgtype.UUID
	TryoutID  pgtype.UUID
	Question  string
	Points    int32
	CreatedAt pgtype.Timestamp
}

type TryoutMcqAttempt struct {
	ID              pgtype.UUID
	TryoutID        pgtype.UUID
	TryoutAttemptID pgtype.UUID
	UserID          pgtype.UUID
	QuestionID      pgtype.UUID
	Answer          pgtype.UUID
	Score           int32
	CreatedAt       pgtype.Timestamp
}

type TryoutMcqOption struct {
	ID         pgtype.UUID
	QuestionID pgtype.UUID
	Option     string
	CreatedAt  pgtype.Timestamp
}

type TryoutMcqQuestion struct {
	ID            pgtype.UUID
	TryoutID      pgtype.UUID
	Question      string
	CorrectAnswer pgtype.UUID
	Points        int32
	CreatedAt     pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	FirstName string
	LastName  string
	CreatedAt pgtype.Timestamp
}
