// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetTryoutById(ctx context.Context, id pgtype.UUID) (*Tryout, error)
	GetTryoutList(ctx context.Context, creatorID pgtype.UUID) ([]*Tryout, error)
	GetTryoutListFiltered(ctx context.Context, arg *GetTryoutListFilteredParams) ([]*Tryout, error)
	GetTryoutQuestionsByTryoutId(ctx context.Context, tryoutID pgtype.UUID) ([][]byte, error)
}

var _ Querier = (*Queries)(nil)
