// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tryout-list-query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTryout = `-- name: DeleteTryout :exec
DELETE FROM tryout
WHERE id = $1
`

func (q *Queries) DeleteTryout(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTryout, id)
	return err
}

const getTryoutById = `-- name: GetTryoutById :one
SELECT id, title, description, long_description, category, duration, difficulty, passing_score, max_attempt, topics, creator_id, created_at, is_published FROM tryout
WHERE id = $1
`

func (q *Queries) GetTryoutById(ctx context.Context, id pgtype.UUID) (*Tryout, error) {
	row := q.db.QueryRow(ctx, getTryoutById, id)
	var i Tryout
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LongDescription,
		&i.Category,
		&i.Duration,
		&i.Difficulty,
		&i.PassingScore,
		&i.MaxAttempt,
		&i.Topics,
		&i.CreatorID,
		&i.CreatedAt,
		&i.IsPublished,
	)
	return &i, err
}

const getTryoutList = `-- name: GetTryoutList :many
SELECT id, title, description, long_description, category, duration, difficulty, passing_score, max_attempt, topics, creator_id, created_at, is_published FROM tryout
WHERE (is_published = true OR creator_id = $1)
ORDER BY created_at DESC
`

func (q *Queries) GetTryoutList(ctx context.Context, creatorID pgtype.UUID) ([]*Tryout, error) {
	rows, err := q.db.Query(ctx, getTryoutList, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tryout{}
	for rows.Next() {
		var i Tryout
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.LongDescription,
			&i.Category,
			&i.Duration,
			&i.Difficulty,
			&i.PassingScore,
			&i.MaxAttempt,
			&i.Topics,
			&i.CreatorID,
			&i.CreatedAt,
			&i.IsPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTryoutListFiltered = `-- name: GetTryoutListFiltered :many
SELECT id, title, description, long_description, category, duration, difficulty, passing_score, max_attempt, topics, creator_id, created_at, is_published FROM tryout
WHERE (is_published = true OR creator_id = $1)
AND difficulty = $2
AND category = $3
AND title ILIKE '%' || $4 || '%'
ORDER BY created_at DESC
`

type GetTryoutListFilteredParams struct {
	CreatorID  pgtype.UUID
	Difficulty pgtype.Text
	Category   pgtype.Text
	Column4    pgtype.Text
}

func (q *Queries) GetTryoutListFiltered(ctx context.Context, arg *GetTryoutListFilteredParams) ([]*Tryout, error) {
	rows, err := q.db.Query(ctx, getTryoutListFiltered,
		arg.CreatorID,
		arg.Difficulty,
		arg.Category,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tryout{}
	for rows.Next() {
		var i Tryout
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.LongDescription,
			&i.Category,
			&i.Duration,
			&i.Difficulty,
			&i.PassingScore,
			&i.MaxAttempt,
			&i.Topics,
			&i.CreatorID,
			&i.CreatedAt,
			&i.IsPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTryout = `-- name: InsertTryout :exec
INSERT INTO tryout (creator_id, title, description, long_description, difficulty, duration, topics, category, is_published, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
`

type InsertTryoutParams struct {
	CreatorID       pgtype.UUID
	Title           string
	Description     pgtype.Text
	LongDescription pgtype.Text
	Difficulty      pgtype.Text
	Duration        pgtype.Int4
	Topics          []string
	Category        pgtype.Text
	IsPublished     bool
}

func (q *Queries) InsertTryout(ctx context.Context, arg *InsertTryoutParams) error {
	_, err := q.db.Exec(ctx, insertTryout,
		arg.CreatorID,
		arg.Title,
		arg.Description,
		arg.LongDescription,
		arg.Difficulty,
		arg.Duration,
		arg.Topics,
		arg.Category,
		arg.IsPublished,
	)
	return err
}

const updateTryout = `-- name: UpdateTryout :exec
UPDATE tryout
SET title = $2,
    description = $3,
    long_description = $4,
    difficulty = $5,
    category = $6,
    is_published = $7,
    duration = $8,
    topics = $9
WHERE id = $1
`

type UpdateTryoutParams struct {
	ID              pgtype.UUID
	Title           string
	Description     pgtype.Text
	LongDescription pgtype.Text
	Difficulty      pgtype.Text
	Category        pgtype.Text
	IsPublished     bool
	Duration        pgtype.Int4
	Topics          []string
}

func (q *Queries) UpdateTryout(ctx context.Context, arg *UpdateTryoutParams) error {
	_, err := q.db.Exec(ctx, updateTryout,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.LongDescription,
		arg.Difficulty,
		arg.Category,
		arg.IsPublished,
		arg.Duration,
		arg.Topics,
	)
	return err
}
